Name:    nginx
Version: 1.0.8
Release: 1%{?dist}
Summary: lightweight web and reverse proxy server

Group:     Applications/Internet
License:   BSD (two-clause)
URL:       http://nginx.org
Source0:   http://nginx.org/download/nginx-%{version}.tar.gz
Source1:   http://github.com/LukeCarrier/rpm-specs/raw/master/SUPPORT/nginx-sysvinit.sh
BuildRoot: %(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

BuildRequires: openssl-devel, pcre-devel, sed, zlib-devel
Requires:      openssl,       pcre,            zlib

%description
nginx [engine x] is a HTTP and reverse proxy server, as well as a mail proxy server written by Igor Sysoev. It has been running since 2004 on many heavily loaded Russian sites including Yandex, Mail.Ru, VKontakte, and Rambler. According to Netcraft nginx served or proxied 7.29% busiest sites in September 2011.


%prep
%setup -q


%build
./configure \
  --with-cc-opt="-w" \
  --prefix=/usr \
  --conf-path=/etc/nginx/nginx.conf \
  --error-log-path=/var/log/nginx/error.log \
  --http-log-path=/var/log/nginx/access.log \
  --lock-path=/var/lock/nginx.lock \
  --pid-path=/var/run/nginx.pid \
  --sbin-path=/usr/sbin/nginx \
  --user=nginx \
  --group=nginx \
  --with-ipv6 \
  --with-http_ssl_module \
  --with-http_stub_status_module
make %{?_smp_mflags}


%install
rm -rf "$RPM_BUILD_ROOT"
make install DESTDIR="$RPM_BUILD_ROOT"

# Move our init script here
#   nginx doesn't ship one, so it's in the repository.
mkdir -p "$RPM_BUILD_ROOT/etc/rc.d/init.d"
cp %{SOURCE1} "$RPM_BUILD_ROOT/etc/rc.d/init.d/nginx"

# Remove default configuration files
#   RPM handles versioning, so we don't need to keep the million and one
#   *.default configuration files generated by Make. We'll handle creating
#   replacement configuration when a backwards incompatible change is released
#   upstream and move all affected files to *.rpmsaves.
etc="$RPM_BUILD_ROOT/etc/nginx"
rm -f \
  "$etc/fastcgi.conf.default" \
  "$etc/fastcgi_params.default" \
  "$etc/mime.types.default" \
  "$etc/nginx.conf.default" \
  "$etc/scgi_params.default" \
  "$etc/uwsgi_params.default"

# Move the document root /var/www/html
#   If the directory seems a bit random, check the (Apache) httpd packages
#   shipped by Red Hat; we're only being consistent.
mkdir -p "$RPM_BUILD_ROOT/var/www"
mv "$RPM_BUILD_ROOT/usr/html" "$RPM_BUILD_ROOT/var/www/html"
sed -i 's%root   html%root   /var/www/html%' "$RPM_BUILD_ROOT/etc/nginx/nginx.conf"


%clean
rm -rf "$RPM_BUILD_ROOT"


%post
# Create the nginx user only if it doesn't exist
#   This is nearly as disgusting as stepping on a slug barefoot.
if [ "$(id nginx >/dev/null 2>&1); echo -n $?" != "0" ]
then
    useradd \
      --comment "nginx web server" \
      --home /var/lib/nginx \
      --create-home \
      --system \
      nginx
    rm -rf /var/lib/nginx/*
fi


%postun
# What goes up must come down and all that...
[ "$(id nginx >/dev/null 2>&1; echo -n $?)" = "0" ] && userdel nginx
[ -d /var/lib/nginx                               ] && rm -rf /var/lib/nginx

%files
%defattr(-, root, root, -)
                   %{_sbindir}/nginx
%attr(755, -, -)   %{_initddir}/nginx
%config(noreplace) %{_sysconfdir}/nginx
%dir               %{_localstatedir}/log/nginx
%config(noreplace) %{_localstatedir}/www/html

%changelog

